export const travel = [
	{
		id: 1,
		city: 'Mountain',
		country: 'Nepal',
		reviews: '4,5',
		weather: 21,
		hotels: '1000$+',
		people: '100,000+',
		img: 'mountain.jpg',
	},
	{
		id: 2,
		city: 'Lake',
		country: 'India',
		reviews: '4,7',
		weather: 25,
		hotels: '1300$+',
		people: '210,000+',
		img: 'lake.jpg',
	},
	{
		id: 3,
		city: 'Paris',
		country: 'France',
		reviews: '4,9',
		weather: 17,
		hotels: '2000$+',
		people: '350,000+',
		img: 'paris.jpg',
	},
	{
		id: 4,
		city: 'Rim',
		country: 'Italia',
		reviews: '4,4',
		weather: 14,
		hotels: '1100$+',
		people: '80,000+',
		img: 'rim.jpg',
	},
	{
		id: 5,
		city: 'Istanbul',
		country: 'Turkey',
		reviews: '4,6',
		weather: 23,
		hotels: '1500$+',
		people: '126,000+',
		img: 'istanbul.jpg',
	},
	{
		id: 6,
		city: 'Los Angeles',
		country: 'Kalifornia',
		reviews: '4,6',
		weather: 17,
		hotels: '1700$+',
		people: '280,000+',
		img: 'losangeles.jpg',
	},
]

export const info = [
	{
		firstText: 'Book and',
		secondText: 'mind your own business',
		img: 'info-1.png',
		infoText: 'Tickets',
		infoDescription: 'Make a booking with us and enjoy',
	},
	{
		firstText: 'We find',
		secondText: 'the best hotels',
		img: 'info-2.png',
		infoText: 'Hotels',
		infoDescription: 'The Ideal Hotel at a Great Price',
	},
	{
		firstText: 'Tours',
		secondText: 'Adventures Activities',
		img: 'info-3.png',
		infoText: 'Adventure',
		infoDescription: 'Find & book tours, adventures, activities',
	},
]
